// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bjY9LBi-8dXyWSHQUxLO55nUinXLK2Y',
    appId: '1:887676015527:web:39f09536b43d496e8a5c82',
    messagingSenderId: '887676015527',
    projectId: 'furrmind',
    authDomain: 'furrmind.firebaseapp.com',
    storageBucket: 'furrmind.firebasestorage.app',
    measurementId: 'G-W2HQ6S9908',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlI4rG7HK6WTulOPYPxPRv9bqua_y6LAY',
    appId: '1:887676015527:android:5933cae6804bb99c8a5c82',
    messagingSenderId: '887676015527',
    projectId: 'furrmind',
    storageBucket: 'furrmind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW9OXe_hShFcHB-VdggKNOfbPhsEId118',
    appId: '1:887676015527:ios:1135fefcb23c39218a5c82',
    messagingSenderId: '887676015527',
    projectId: 'furrmind',
    storageBucket: 'furrmind.firebasestorage.app',
    iosClientId: '887676015527-kqp3f4mbpd36rorjklgf9ocsublss15v.apps.googleusercontent.com',
    iosBundleId: 'com.furrmind.furrmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW9OXe_hShFcHB-VdggKNOfbPhsEId118',
    appId: '1:887676015527:ios:1135fefcb23c39218a5c82',
    messagingSenderId: '887676015527',
    projectId: 'furrmind',
    storageBucket: 'furrmind.firebasestorage.app',
    iosClientId: '887676015527-kqp3f4mbpd36rorjklgf9ocsublss15v.apps.googleusercontent.com',
    iosBundleId: 'com.furrmind.furrmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_bjY9LBi-8dXyWSHQUxLO55nUinXLK2Y',
    appId: '1:887676015527:web:04ac71f1dd3f871e8a5c82',
    messagingSenderId: '887676015527',
    projectId: 'furrmind',
    authDomain: 'furrmind.firebaseapp.com',
    storageBucket: 'furrmind.firebasestorage.app',
    measurementId: 'G-ENLJLSHK0T',
  );
}
